FlOpEDT/api/people/urls.py
# This file is part of the FlOpEDT/FlOpScheduler project.
# Copyright (c) 2017
# Authors: Iulian Ober, Paul Renaud-Goud, Pablo Seban, et al.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License along with this program. If not, see
# <http://www.gnu.org/licenses/>.
#
# You can be released from the requirements of the license by purchasing
# a commercial license. Buying such a license is mandatory as soon as
# you develop activities involving the FlOpEDT/FlOpScheduler software
# without disclosing the source code of your own applications.
from rest_framework import routers

from api.people import views
import api.preferences.views as views_preferences

routerPeople = routers.SimpleRouter()

routerPeople.register(r'users', views.UsersViewSet)
routerPeople.register(r'userdepartmentsettings', views.UserDepartmentSettingsViewSet)
routerPeople.register(r'tutor/username', views.TutorUsernameViewSet, basename='tutor_username')
routerPeople.register(r'tutor', views.TutorViewSet, basename='tutor')
routerPeople.register(r'supplystaff', views.SupplyStaffsViewSet)
routerPeople.register(r'students', views.StudentsViewSet)
routerPeople.register(r'studentsinfo', views.StudentInfoViewSet)
#routerPeople.register(r'coursepreferences', views_preferences.CoursePreferencesViewSet)

FlOpEDT/api/urls.py
# This file is part of the FlOpEDT/FlOpScheduler project.
# Copyright (c) 2017
# Authors: Iulian Ober, Paul Renaud-Goud, Pablo Seban, et al.
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public
# License along with this program. If not, see
# <http://www.gnu.org/licenses/>.
# 
# You can be released from the requirements of the license by purchasing
# a commercial license. Buying such a license is mandatory as soon as
# you develop activities involving the FlOpEDT/FlOpScheduler software
# without disclosing the source code of your own applications.

from django.conf.urls import include, url
from django.contrib.auth.decorators import login_required
from django.urls import path
from django.views.generic import TemplateView
from drf_yasg import openapi
# from rest_framework_swagger.renderers import SwaggerUIRenderer, OpenAPIRenderer
from drf_yasg.views import get_schema_view
from rest_framework import routers, permissions
from rest_framework.authtoken.views import obtain_auth_token

import api.base.views as views_base
import api.fetch.views as views_fetch
from api import views
from api.TTapp.urls import routerTTapp
from api.base.courses.urls import routerCourses
from api.base.groups.urls import routerGroups
from api.base.rooms.urls import routerRooms
from api.base.urls import routerBase
from api.fetch.urls import routerFetch
from api.myflop.urls import routerMyFlop
from api.people.urls import routerPeople
from api.preferences.urls import routerPreferences
from api.roomreservation.urls import routerRoomReservation

#####################################
# URLS based on django applications #
#####################################

app_name = "api"

routerDisplayweb = routers.SimpleRouter()

routerDisplayweb.register(r'breakingnews', views.BreakingNewsViewSet)
routerDisplayweb.register(r'moduledisplays', views.ModuleDisplaysViewSet)
routerDisplayweb.register(r'trainingprogrammedisplays', views.TrainingProgrammeDisplaysViewSet)
routerDisplayweb.register(r'groupdisplays', views.GroupDisplaysViewSet)

######################
# User friendly URLS #
######################

routerExtra = routers.SimpleRouter()

routerExtra.register('bknews', views_fetch.BKNewsViewSet, basename="bknews")
routerExtra.register('quote/random', views.RandomQuoteViewSet, basename="random-quote")
routerExtra.register('quote', views.QuoteViewSet)
routerExtra.register('week-infos', views.WeekInfoViewSet, basename="week-infos")

################
# SWAGGER VIEW #
################
schema_view = get_schema_view(
    openapi.Info(
        title="Snippets API",
        default_version='v1',
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    url(r'^$', views_base.LoginView.as_view(), name='api_root'),
    url(r'^logout/$', views_base.LogoutView.as_view()),
    url(r'^backoffice/$', login_required(TemplateView.as_view(template_name='logout.html'))),
    path('base/', include((routerBase.urls, 'api'), namespace='base')),
    path('user/', include((routerPeople.urls, 'api'), namespace="people")),
    path('display/', include(routerDisplayweb.urls)),
    path('ttapp/', include((routerTTapp.urls, 'api'), namespace='ttapp')),
    path('fetch/',
         include((routerFetch.urls, 'api'), namespace='fetch')),
    path('rest-auth/', include('rest_auth.urls')),
    path('api-token-auth/', obtain_auth_token, name='api_token_auth'),
    url('doc/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('preferences/', include(routerPreferences.urls)),
    path('rooms/',
         include((routerRooms.urls, 'api'), namespace='rooms')),
    path('courses/',
         include((routerCourses.urls, 'api'), namespace='course')),
    path('groups/',
         include((routerGroups.urls, 'api'), namespace='groups')),
    path('extra/',
         include((routerExtra.urls, 'api'), namespace='extra')),
    path('myflop/',
         include((routerMyFlop.urls, 'api'), namespace='myflop')),
    path('roomreservations/',
         include((routerRoomReservation.urls, 'api'), namespace='roomreservations')),
]

FlOpEDT/people/urls.py
# -*- coding: utf-8 -*-

# This file is part of the FlOpEDT/FlOpScheduler project.
# Copyright (c) 2017
# Authors: Iulian Ober, Paul Renaud-Goud, Pablo Seban, et al.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License along with this program. If not, see
# <http://www.gnu.org/licenses/>.
#
# You can be released from the requirements of the license by purchasing
# a commercial license. Buying such a license is mandatory as soon as
# you develop activities involving the FlOpEDT/FlOpScheduler software
# without disclosing the source code of your own applications.

from django.urls import path
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from django.views.generic.base import RedirectView
from people.student import ChangeStudent
from people.tutor import ChangeFullStaffTutor, ChangeSupplyStaffTutor, ChangeBIATOSTutor
from . import views

app_name="people"

urlpatterns = [
#    url(r'^login', views.login, name="login"),
    url(r'^login/$',
        auth_views.LoginView.as_view(template_name='people/login.html'),
        name='login'),
    url(r'^logout/$',
        auth_views.LogoutView.as_view( next_page= '/'),
        name='logout'),
    url(r'^password-reset/$',
        auth_views.PasswordResetView.as_view(
            template_name='people/password_reset_form.html',
            email_template_name='people/password_reset_email.html',
            subject_template_name='people/password_reset_subject.txt',
            success_url=reverse_lazy('people:password_reset_done')),
        name='password_reset'),
    url(r'^pwd-reset-done/$',
        auth_views.PasswordResetDoneView.as_view(
            template_name='people/password_reset_done.html'),
        name='password_reset_done'),
    url(r'^pwd-reset-complete/$',
        auth_views.PasswordResetCompleteView.as_view(
            template_name='people/password_reset_complete.html'),
        name='password_reset_complete'),
    url(r'^password-change/$',
        auth_views.PasswordChangeView.as_view(
            template_name='people/password_change_form.html',
            success_url=reverse_lazy('people:password_change_done')),
        name='password_change'),
    url(r'^pwd-chg-done/$',
        auth_views.PasswordChangeDoneView.as_view(
            template_name='people/password_change_done.html'),
        name='password_change_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/'
        r'(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='people/password_reset_confirm.html',
            success_url=reverse_lazy('people:password_reset_complete')),
        name='password_reset_confirm'),
    url(r'^change/some/$',
        views.redirect_change_people_kind,
        name="change_redirect"),
    url(r'^change/student/$',
        ChangeStudent.as_view(),
        name="change_student"),
    url(r'^change/fullstaff/$',
        ChangeFullStaffTutor.as_view(),
        name="change_fullstaff"),
    url(r'^change/supplystaff/$',
        ChangeSupplyStaffTutor.as_view(),
        name="change_supplystaff"),
    url(r'^change/biatos/$',
        ChangeBIATOSTutor.as_view(),
        name="change_BIATOS"),
    url(r'^fetch_tutors/$',
        views.fetch_tutors,
        name="fetch_tutors"),
    url(r'^fetch_preferences_group/$',
        views.fetch_preferences_group,
        name="fetch_preferences_group"),
    url(r'^fetch_preferences_students/$',
        views.fetch_preferences_students,
        name="fetch_preferences_students"),
    path('fetch_user_preferred_links/<str:department>',
         views.fetch_user_preferred_links,
         name='fetch_user_preferred_links'),
    url(r'^student_preferences/$',
        views.student_preferences,
        name="student_preferences"),
    path('profile/', RedirectView.as_view(pattern_name="index", permanent=False)),
    path('fetch_physical_presence/<str:department>/<int:year>/<int:week>',
         views.fetch_physical_presence,
         name='fetch_physical_presence'),
    path('change_physical_presence/<int:year>/<int:week_nb>/<str:user>',
         views.change_physical_presence,
         name='change_physical_presence')
    ]

FlOpEDT/api/people/views.py
# This file is part of the FlOpEDT/FlOpScheduler project.
# Copyright (c) 2017
# Authors: Iulian Ober, Paul Renaud-Goud, Pablo Seban, et al.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License along with this program. If not, see
# <http://www.gnu.org/licenses/>.
#
# You can be released from the requirements of the license by purchasing
# a commercial license. Buying such a license is mandatory as soon as
# you develop activities involving the FlOpEDT/FlOpScheduler software
# without disclosing the source code of your own applications.
from django.utils.decorators import method_decorator
import django_filters.rest_framework as filters
from drf_yasg.utils import swagger_auto_schema
from rest_framework import viewsets
from rest_framework.permissions import IsAuthenticated


import people.models as pm
import base.models as bm
from api.people import serializers
from api.shared.params import week_param, year_param

from api.permissions import IsTutorOrReadOnly, IsAdminOrReadOnly


class UsersViewSet(viewsets.ModelViewSet):
    """
    ViewSet to see all the users

    Can be filtered as wanted with every field of a User object.
    """
    permission_classes = [IsAdminOrReadOnly]
    queryset = pm.User.objects.all()
    serializer_class = serializers.UsersSerializer


class UserDepartmentSettingsViewSet(viewsets.ModelViewSet):
    """
    ViewSet to see all the user department settings
    which shows the combination of the user and the department

    Can be filtered as wanted with every field of a User Department object.
    """
    permission_classes = [IsAdminOrReadOnly]
    queryset = pm.UserDepartmentSettings.objects.all()
    serializer_class = serializers.UserDepartmentSettingsSerializer


class SupplyStaffsViewSet(viewsets.ModelViewSet):
    """
    ViewSet to see all the supply staff

    Can be filtered as wanted with every field of a Supply Staff object.
    """
    permission_classes = [IsAdminOrReadOnly]
    queryset = pm.SupplyStaff.objects.all()
    serializer_class = serializers.SupplyStaffsSerializer


class StudentsViewSet(viewsets.ModelViewSet):
    """
    ViewSet to see all the students

    Can be filtered as wanted with every field of a Student object.
    """
    permission_classes = [IsAdminOrReadOnly]
    queryset = pm.Student.objects.all()
    serializer_class = serializers.StudentsSerializer


class StudentInfoViewSet(viewsets.ModelViewSet):
    """
    ViewSet to see all info of one student
    """
    permission_classes = [IsAdminOrReadOnly]
    queryset = pm.Student.objects.all()
    serializer_class = serializers.StudentInfoSerializer


# class StudentPreferencesViewSet(viewsets.ModelViewSet):
#     """
#     ViewSet to see all the students' preferences.

#     Can be filtered as wanted with every field of a StudentPreference object.
#     """
#     permission_classes = (IsAuthenticated,)
#     serializer_class = serializers.StudentPreferencesSerializer
#     filterset_fields = '__all__'

#     def get_queryset(self):
#         # Creating a queryset containing every StudentPreference
#         qs = pm.StudentPreferences.objects.all()

#         # Getting the filters
#         username = self.request.query_params.get('username', None)

#         # Applying filters
#         if username == None:
#             return None
#         return qs.filter(username=username)


# class GroupPreferencesViewSet(viewsets.ModelViewSet):
#     """
#     ViewSet to see all the groups' preferences.

#     Can be filtered as wanted with every field of a GroupPreference object.
#     """
#     permission_classes = (IsAuthenticated,)
#     queryset = pm.GroupPreferences.objects.all()
#     serializer_class = serializers.GroupPreferencesSerializer


class TutorFilterSet(filters.FilterSet):
    permission_classes = [IsTutorOrReadOnly]
    dept = filters.CharFilter(field_name='departments__abbrev', required=True)

    class Meta:
        model = pm.Tutor
        fields = ['dept']


class TutorUsernameViewSet(viewsets.ReadOnlyModelViewSet):
    """
    ViewSet to see all the tutors

    Can be filtered as wanted with every field of a Tutor object.
    """
    permission_classes = [IsAdminOrReadOnly]

    queryset = pm.Tutor.objects.all()
    serializer_class = serializers.TutorUsernameSerializer
    filter_class = TutorFilterSet


@method_decorator(name='list',
                  decorator=swagger_auto_schema(
                      operation_description="Active tutors",
                      manual_parameters=[week_param(), year_param()])
                  )
class TutorViewSet(viewsets.ModelViewSet):
    def get_queryset(self):
        # Getting all the filters
        week = self.request.query_params.get('week', None)
        year = self.request.query_params.get('year', None)

        # Filtering
        if week is not None and year is not None:
            return pm.Tutor.objects.filter(
                pk__in=bm.ScheduledCourse.objects.filter(
                    course__week__nb=week,
                    course__week__year=year,
                    work_copy=0) \
                    .distinct('tutor').values('tutor')
            )
        else:
            return pm.Tutor.objects.all()

    serializer_class = serializers.TutorSerializer
    filter_class = TutorFilterSet
    permission_classes = [IsAdminOrReadOnly]

FlOpEDT/people/templates/people/changeuser.html
<!-- This file is part of the FlOpEDT/FlOpScheduler project.               -->
<!-- Copyright (c) 2017                                                    -->
<!-- Authors: Iulian Ober, Paul Renaud-Goud, Pablo Seban, et al.           -->
<!--                                                                       -->
<!-- This program is free software: you can redistribute it and/or modify  -->
<!-- it under the terms of the GNU Affero General Public License as        -->
<!-- published by the Free Software Foundation, either version 3 of the    -->
<!-- License, or (at your option) any later version.                       -->
<!--                                                                       -->
<!-- This program is distributed in the hope that it will be useful, but   -->
<!-- WITHOUT ANY WARRANTY; without even the implied warranty of            -->
<!-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU      -->
<!-- Affero General Public License for more details.                       -->
<!--                                                                       -->
<!-- You should have received a copy of the GNU Affero General Public      -->
<!-- License along with this program. If not, see                          -->
<!-- <http://www.gnu.org/licenses/>.                                       -->
<!--                                                                       -->
<!-- You can be released from the requirements of the license by purchasing -->
<!-- a commercial license. Buying such a license is mandatory as soon as   -->
<!-- you develop activities involving the FlOpEDT/FlOpScheduler software   -->
<!-- without disclosing the source code of your own applications.          -->

{% extends "base.html" %}

{% block content %}

<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>

{% endblock %}

FlOpEDT/people/templates/people/login.html
<!-- This file is part of the FlOpEDT/FlOpScheduler project.               -->
<!-- Copyright (c) 2017                                                    -->
<!-- Authors: Iulian Ober, Paul Renaud-Goud, Pablo Seban, et al.           -->
<!--                                                                       -->
<!-- This program is free software: you can redistribute it and/or modify  -->
<!-- it under the terms of the GNU Affero General Public License as        -->
<!-- published by the Free Software Foundation, either version 3 of the    -->
<!-- License, or (at your option) any later version.                       -->
<!--                                                                       -->
<!-- This program is distributed in the hope that it will be useful, but   -->
<!-- WITHOUT ANY WARRANTY; without even the implied warranty of            -->
<!-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU      -->
<!-- Affero General Public License for more details.                       -->
<!--                                                                       -->
<!-- You should have received a copy of the GNU Affero General Public      -->
<!-- License along with this program. If not, see                          -->
<!-- <http://www.gnu.org/licenses/>.                                       -->
<!--                                                                       -->
<!-- You can be released from the requirements of the license by purchasing -->
<!-- a commercial license. Buying such a license is mandatory as soon as   -->
<!-- you develop activities involving the FlOpEDT/FlOpScheduler software   -->
<!-- without disclosing the source code of your own applications.          -->

{% extends "base.html" %}
{% load i18n %}

{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static "base/better.css" %}"/>
  
  
<div id="tools-main" style="padding:10px;">

  <div style="float: left; width:400px">    
    <fieldset style="width:300px">
      <legend>Authentification</legend>
      <form method="post" action="{% url 'people:login' %}" name="login">
	{% csrf_token %}
	<table>
	  <tr>
            <td>{{ form.username.label_tag }}</td>
            <td>{{ form.username }}</td>
	  </tr>
	  <tr>
            <td>{{ form.password.label_tag }}</td>
            <td>{{ form.password }}</td>
	  </tr>
	</table>
	
	<span>
          <a href="{% url 'people:password_reset' %}">
            {% trans "Forgot password?" %}
          </a>
        </span>
	<input style="float:right" type="submit" value="{% trans 'Sign in' %}"/>
	<input type="hidden" name="next" value="{{ next }}"/>
      </form>
    </fieldset>
  </div>
  <div style="float: left; width:300px">
    {% if form.errors %}
    <p>Pas de correspondance entre le pseudo et le mot de passe. Réessayer.</p>
    {% endif %}
    
    {% if next %}
    {% if user.is_authenticated %}
    <p>Your account doesn't have access to this page. To proceed,
      please login with an account that has access.</p>
    {% endif %}
    {% endif %}
    <p></p>
  </div>
</div>
{% endblock %}

FlOpEDT/people/templates/people/password_reset_complete.html
<!-- This file is part of the FlOpEDT/FlOpScheduler project.               -->
<!-- Copyright (c) 2017                                                    -->
<!-- Authors: Iulian Ober, Paul Renaud-Goud, Pablo Seban, et al.           -->
<!--                                                                       -->
<!-- This program is free software: you can redistribute it and/or modify  -->
<!-- it under the terms of the GNU Affero General Public License as        -->
<!-- published by the Free Software Foundation, either version 3 of the    -->
<!-- License, or (at your option) any later version.                       -->
<!--                                                                       -->
<!-- This program is distributed in the hope that it will be useful, but   -->
<!-- WITHOUT ANY WARRANTY; without even the implied warranty of            -->
<!-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU      -->
<!-- Affero General Public License for more details.                       -->
<!--                                                                       -->
<!-- You should have received a copy of the GNU Affero General Public      -->
<!-- License along with this program. If not, see                          -->
<!-- <http://www.gnu.org/licenses/>.                                       -->
<!--                                                                       -->
<!-- You can be released from the requirements of the license by purchasing -->
<!-- a commercial license. Buying such a license is mandatory as soon as   -->
<!-- you develop activities involving the FlOpEDT/FlOpScheduler software   -->
<!-- without disclosing the source code of your own applications.          -->

{% extends "base.html" %}

{% block title %}
Mot de passe oublié
{% endblock %}

{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static "base/better.css" %}"/>
    <p>
      Le mot de passe a été changé.<br/>
      <a href="{% url 'people:login' %}">
	Se connecter
      </a>
    </p>

{% endblock %}

FlOpEDT/people/templates/people/password_reset_confirm.html
<!-- This file is part of the FlOpEDT/FlOpScheduler project.               -->
<!-- Copyright (c) 2017                                                    -->
<!-- Authors: Iulian Ober, Paul Renaud-Goud, Pablo Seban, et al.           -->
<!--                                                                       -->
<!-- This program is free software: you can redistribute it and/or modify  -->
<!-- it under the terms of the GNU Affero General Public License as        -->
<!-- published by the Free Software Foundation, either version 3 of the    -->
<!-- License, or (at your option) any later version.                       -->
<!--                                                                       -->
<!-- This program is distributed in the hope that it will be useful, but   -->
<!-- WITHOUT ANY WARRANTY; without even the implied warranty of            -->
<!-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU      -->
<!-- Affero General Public License for more details.                       -->
<!--                                                                       -->
<!-- You should have received a copy of the GNU Affero General Public      -->
<!-- License along with this program. If not, see                          -->
<!-- <http://www.gnu.org/licenses/>.                                       -->
<!--                                                                       -->
<!-- You can be released from the requirements of the license by purchasing -->
<!-- a commercial license. Buying such a license is mandatory as soon as   -->
<!-- you develop activities involving the FlOpEDT/FlOpScheduler software   -->
<!-- without disclosing the source code of your own applications.          -->

{% extends "base.html" %}

{% block title %}
Mot de passe oublié
{% endblock %}

{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static "base/better.css" %}"/>
  {% if validlink %}
    <h3>Change password</h3>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Changer le mot de passe</button>
    </form>
  {% else %}
    <p>
      L'adresse de réinitialisation est invalide (déjà utilisée, par exemple).
      <a href="{% url 'people:password_reset'%}">
	Réréinitialiser !
      </a>
    </p>
  {% endif %}

{% endblock %}

FlOpEDT/people/templates/people/password_reset_email.html
{% autoescape off %}
Pour réinitialiser votre mot de passe associé à votre compte {{ user.get_username }} sur FlOpEDT, accéder au lien suivant :

{{ protocol }}://{{ domain }}{% url 'people:password_reset_confirm' uidb64=uid token=token %}

(Soit en cliquant dessus, soit en copiant-collant l'adresse dans un navigateur quelconque.)
{% endautoescape %}

FlOpEDT/people/templates/people/studentPreferencesSelection.html
<!-- This file is part of the FlOpEDT/FlOpScheduler project.               -->
<!-- Copyright (c) 2017                                                    -->
<!-- Authors: Iulian Ober, Paul Renaud-Goud, Pablo Seban, et al.           -->
<!--                                                                       -->
<!-- This program is free software: you can redistribute it and/or modify  -->
<!-- it under the terms of the GNU Affero General Public License as        -->
<!-- published by the Free Software Foundation, either version 3 of the    -->
<!-- License, or (at your option) any later version.                       -->
<!--                                                                       -->
<!-- This program is distributed in the hope that it will be useful, but   -->
<!-- WITHOUT ANY WARRANTY; without even the implied warranty of            -->
<!-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU      -->
<!-- Affero General Public License for more details.                       -->
<!--                                                                       -->
<!-- You should have received a copy of the GNU Affero General Public      -->
<!-- License along with this program. If not, see                          -->
<!-- <http://www.gnu.org/licenses/>.                                       -->
<!--                                                                       -->
<!-- You can be released from the requirements of the license by purchasing -->
<!-- a commercial license. Buying such a license is mandatory as soon as   -->
<!-- you develop activities involving the FlOpEDT/FlOpScheduler software   -->
<!-- without disclosing the source code of your own applications.          -->



{% extends "base.html" %}

{% load static %}
{% load i18n %}

<script href="https://code.jquery.com/jquery-3.3.1.js"></script>


{% block title %} {% trans "Student Preferences" %} {% endblock %}

{% block content %}

</br></br></br>

<form action="{% url 'people:student_preferences' %}" method="post" id="form_pref">
  {% csrf_token %}
  <fieldset>
    <legend>{% trans "Preferences for your group" %}</legend>
      </br>
      <div><b> {% trans "Morning or evening?" %}</b></div>
      <div>

        <input type="range" id="morning" name="morning_evening" min="0" max="1" step="0.25" value="{{ morning|stringformat:'.2f' }}"/>
        <output name="result">{{ morning_txt }}</output>
      </div>
        </br>
      <div><b>{% trans "Busy days VS Free half-days" %}</b></div>

      <div>

        <input type="range" id="free_half_day" name="light_free" min="0" max="1" step="0.25" value="{{ free_half_day|stringformat:'.2f' }}"/>
        <output name="resultdeux">{{ free_half_day_txt }}</output>
      </div>
        </br>
      <div><b>{% trans "Holes?" %}</b></div>
      <div>
        <input type="range" id="hole" name="hole_nothole" min="0" max="1" step="0.5" value="{{ hole|stringformat:'.2f' }}"/>
        <output name="resulthole">{{ hole_txt }}</output>
      </div>
        <br/>
      <div><b>{% trans "Eat early or late?" %}</b></div>

      <div>
        <input type="range" id="selfeat" name="eat" min="0" max="1" step="0.5"
        value="{{ selfeat|stringformat:'.2f' }}"/>
        <output name="resulteat">{{ eat_txt }}</output>
      </div>
        <br/><br/>
      <button type="submit" form="form_pref" value="Submit">Valider</button>
  </fieldset>

{% comment %}
    <fieldset class="twofieldset">
      <legend>Préférences demi-journée libre</legend>
        <br/>
      <div>Indiquez <b>en rouge</b> les demies-journées pour lesquels avoir cours est <b>moins souhaitable</b>...</div>
        <div align="center">
          <svg id="grille">

          </svg>
        </div>
        <button class="rightbutton" type="submit" form="form_pref" value="Submit">Valider</button>
    </fieldset>
 {% endcomment %}

</form>


<br/><br/>
{% include 'base/notification.html' %}

{# Themes #}
{% include 'base/themes.html' %}

<link rel="stylesheet" type="text/css" href="{% static 'people/student_preferences.css' %}"/>
<script src="{% static 'people/student_preferences.js' %}"></script>

{% endblock %}